### ISSUE TITLE
[PROPOSAL] Add release for last version with supports Swift 2.x

### ISSUE THREAD

**Issue by x0000ff** [jakarmy/swift-summary#14]
I think it will be useful to add a tag, create a release for the last version with support Swift 2.x.
I guess it was: https://github.com/jakarmy/swift-summary/commit/2be0e47d8ebba4716b292a573d93333d1e0a88c0

Regrettably I can't do it via a Pull Request. @jakarmy, If you need help with it - feel free to contact me.

¡Muchas gracias por el repositorio!

**Comment by jakarmy** [comment]
Hey @x0000ff, thanks for the suggestion.
Can you provide an example for adding that tag?
Thanks!

**Comment by x0000ff** [comment]
I made a screencast:
[https://youtu.be/cNHGmH4J-tM](https://youtu.be/cNHGmH4J-tM)

Small hints for you:

# Add tag

```
$ git tag -a -m "" v1.1 c5b4907dd75d2b610401f6787a39e5000d6f56e6 
```

# Push all tags

```
$ git push origin --tags
```

# Delete tag

```
$ git tag -d v1.1 
$ git push -v origin :refs/tags/v1.1
```

**Comment by jakarmy** [comment]
Thank you so much for these great hints!
Just added 3 tags, v1.0, v1.1 and v1.2.

**Comment by x0000ff** [comment]
Great, @jakarmy 🎉 🍻
